version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: airecruiter-postgres
    environment:
      POSTGRES_DB: airecruiter
      POSTGRES_USER: airecruiter_user
      POSTGRES_PASSWORD: airecruiter_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: airecruiter-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airecruiter-api
    depends_on:
      - postgres
      - redis
      - ai-feedback-service
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - .env
    environment:
      - AI_SERVICE_URL=http://airecruiter-ml:8000

  ai-feedback-service:
    build:
      context: ../ai-recruiter-ml
    container_name: airecruiter-ml
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3g

volumes:
  postgres_data: