server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/airecruiter
    username: airecruiter_user
    password: airecruiter_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
      pool-name: HikariPool

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: airecruiter
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
